package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseGroupResource;

public interface BaseGroupResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    int insert(BaseGroupResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    int insertSelective(BaseGroupResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    BaseGroupResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseGroupResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseGroupResource record);
}