package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseGroupType;

public interface BaseGroupTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    int insert(BaseGroupType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    int insertSelective(BaseGroupType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    BaseGroupType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseGroupType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseGroupType record);
}