package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseGroupMember;

public interface BaseGroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    int insert(BaseGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    int insertSelective(BaseGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    BaseGroupMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseGroupMember record);
}