package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseGroup;

public interface BaseGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    int insert(BaseGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    int insertSelective(BaseGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    BaseGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseGroup record);
}