package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseResource;

public interface BaseResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    int insert(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    int insertSelective(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    BaseResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseResource record);
}