package com.youmel.auth.mapper;

import com.youmel.auth.pojo.BaseResourceAuthority;

public interface BaseResourceAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    int insert(BaseResourceAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    int insertSelective(BaseResourceAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    BaseResourceAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseResourceAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseResourceAuthority record);
}