package com.youmel.auth.mapper;

import com.youmel.auth.pojo.GateLog;

public interface GateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    int insert(GateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    int insertSelective(GateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    GateLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GateLog record);
}