package com.youmel.auth.mapper;

import com.youmel.auth.pojo.TOrganizationUser;

public interface TOrganizationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    int insert(TOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    int insertSelective(TOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    TOrganizationUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrganizationUser record);
}