package com.youmel.auth.mapper;

import com.youmel.auth.pojo.TOrganization;

public interface TOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    int insert(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    int insertSelective(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    TOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrganization record);
}