package com.youmel.auth.pojo;

import java.util.Date;

public class BaseMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.href
     *
     * @mbggenerated
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.enabled
     *
     * @mbggenerated
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_name
     *
     * @mbggenerated
     */
    private String crtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_time
     *
     * @mbggenerated
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_user
     *
     * @mbggenerated
     */
    private String updUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_name
     *
     * @mbggenerated
     */
    private String updName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_host
     *
     * @mbggenerated
     */
    private String updHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr6
     *
     * @mbggenerated
     */
    private String attr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr7
     *
     * @mbggenerated
     */
    private String attr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr8
     *
     * @mbggenerated
     */
    private String attr8;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    public BaseMenu(Integer id, String code, String title, Integer parentId, String href, String icon, String type, Integer orderNum, String description, String path, String enabled, Date crtTime, String crtUser, String crtName, String crtHost, Date updTime, String updUser, String updName, String updHost, String attr1, String attr2, String attr3, String attr4, String attr5, String attr6, String attr7, String attr8) {
        this.id = id;
        this.code = code;
        this.title = title;
        this.parentId = parentId;
        this.href = href;
        this.icon = icon;
        this.type = type;
        this.orderNum = orderNum;
        this.description = description;
        this.path = path;
        this.enabled = enabled;
        this.crtTime = crtTime;
        this.crtUser = crtUser;
        this.crtName = crtName;
        this.crtHost = crtHost;
        this.updTime = updTime;
        this.updUser = updUser;
        this.updName = updName;
        this.updHost = updHost;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
        this.attr4 = attr4;
        this.attr5 = attr5;
        this.attr6 = attr6;
        this.attr7 = attr7;
        this.attr8 = attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    public BaseMenu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.id
     *
     * @return the value of base_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.id
     *
     * @param id the value for base_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.code
     *
     * @return the value of base_menu.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.code
     *
     * @param code the value for base_menu.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.title
     *
     * @return the value of base_menu.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.title
     *
     * @param title the value for base_menu.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.parent_id
     *
     * @return the value of base_menu.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.parent_id
     *
     * @param parentId the value for base_menu.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.href
     *
     * @return the value of base_menu.href
     *
     * @mbggenerated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.href
     *
     * @param href the value for base_menu.href
     *
     * @mbggenerated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.icon
     *
     * @return the value of base_menu.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.icon
     *
     * @param icon the value for base_menu.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.type
     *
     * @return the value of base_menu.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.type
     *
     * @param type the value for base_menu.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.order_num
     *
     * @return the value of base_menu.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.order_num
     *
     * @param orderNum the value for base_menu.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.description
     *
     * @return the value of base_menu.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.description
     *
     * @param description the value for base_menu.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.path
     *
     * @return the value of base_menu.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.path
     *
     * @param path the value for base_menu.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.enabled
     *
     * @return the value of base_menu.enabled
     *
     * @mbggenerated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.enabled
     *
     * @param enabled the value for base_menu.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_time
     *
     * @return the value of base_menu.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_time
     *
     * @param crtTime the value for base_menu.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_user
     *
     * @return the value of base_menu.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_user
     *
     * @param crtUser the value for base_menu.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_name
     *
     * @return the value of base_menu.crt_name
     *
     * @mbggenerated
     */
    public String getCrtName() {
        return crtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_name
     *
     * @param crtName the value for base_menu.crt_name
     *
     * @mbggenerated
     */
    public void setCrtName(String crtName) {
        this.crtName = crtName == null ? null : crtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_host
     *
     * @return the value of base_menu.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_host
     *
     * @param crtHost the value for base_menu.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_time
     *
     * @return the value of base_menu.upd_time
     *
     * @mbggenerated
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_time
     *
     * @param updTime the value for base_menu.upd_time
     *
     * @mbggenerated
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_user
     *
     * @return the value of base_menu.upd_user
     *
     * @mbggenerated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_user
     *
     * @param updUser the value for base_menu.upd_user
     *
     * @mbggenerated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_name
     *
     * @return the value of base_menu.upd_name
     *
     * @mbggenerated
     */
    public String getUpdName() {
        return updName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_name
     *
     * @param updName the value for base_menu.upd_name
     *
     * @mbggenerated
     */
    public void setUpdName(String updName) {
        this.updName = updName == null ? null : updName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_host
     *
     * @return the value of base_menu.upd_host
     *
     * @mbggenerated
     */
    public String getUpdHost() {
        return updHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_host
     *
     * @param updHost the value for base_menu.upd_host
     *
     * @mbggenerated
     */
    public void setUpdHost(String updHost) {
        this.updHost = updHost == null ? null : updHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr1
     *
     * @return the value of base_menu.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr1
     *
     * @param attr1 the value for base_menu.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr2
     *
     * @return the value of base_menu.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr2
     *
     * @param attr2 the value for base_menu.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr3
     *
     * @return the value of base_menu.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr3
     *
     * @param attr3 the value for base_menu.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr4
     *
     * @return the value of base_menu.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr4
     *
     * @param attr4 the value for base_menu.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr5
     *
     * @return the value of base_menu.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr5
     *
     * @param attr5 the value for base_menu.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr6
     *
     * @return the value of base_menu.attr6
     *
     * @mbggenerated
     */
    public String getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr6
     *
     * @param attr6 the value for base_menu.attr6
     *
     * @mbggenerated
     */
    public void setAttr6(String attr6) {
        this.attr6 = attr6 == null ? null : attr6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr7
     *
     * @return the value of base_menu.attr7
     *
     * @mbggenerated
     */
    public String getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr7
     *
     * @param attr7 the value for base_menu.attr7
     *
     * @mbggenerated
     */
    public void setAttr7(String attr7) {
        this.attr7 = attr7 == null ? null : attr7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr8
     *
     * @return the value of base_menu.attr8
     *
     * @mbggenerated
     */
    public String getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr8
     *
     * @param attr8 the value for base_menu.attr8
     *
     * @mbggenerated
     */
    public void setAttr8(String attr8) {
        this.attr8 = attr8 == null ? null : attr8.trim();
    }
}