package com.youmel.auth.pojo;

public class BaseGroupResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.resource_id
     *
     * @mbggenerated
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.resource_type
     *
     * @mbggenerated
     */
    private Integer resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.crt_time
     *
     * @mbggenerated
     */
    private Integer crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.crt_uid
     *
     * @mbggenerated
     */
    private Integer crtUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_resource.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    public BaseGroupResource(Integer id, Integer groupId, Integer resourceId, Integer resourceType, Integer crtTime, Integer crtUid, String crtHost, String attr1, String attr2, String attr3) {
        this.id = id;
        this.groupId = groupId;
        this.resourceId = resourceId;
        this.resourceType = resourceType;
        this.crtTime = crtTime;
        this.crtUid = crtUid;
        this.crtHost = crtHost;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_resource
     *
     * @mbggenerated
     */
    public BaseGroupResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.id
     *
     * @return the value of base_group_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.id
     *
     * @param id the value for base_group_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.group_id
     *
     * @return the value of base_group_resource.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.group_id
     *
     * @param groupId the value for base_group_resource.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.resource_id
     *
     * @return the value of base_group_resource.resource_id
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.resource_id
     *
     * @param resourceId the value for base_group_resource.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.resource_type
     *
     * @return the value of base_group_resource.resource_type
     *
     * @mbggenerated
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.resource_type
     *
     * @param resourceType the value for base_group_resource.resource_type
     *
     * @mbggenerated
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.crt_time
     *
     * @return the value of base_group_resource.crt_time
     *
     * @mbggenerated
     */
    public Integer getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.crt_time
     *
     * @param crtTime the value for base_group_resource.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Integer crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.crt_uid
     *
     * @return the value of base_group_resource.crt_uid
     *
     * @mbggenerated
     */
    public Integer getCrtUid() {
        return crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.crt_uid
     *
     * @param crtUid the value for base_group_resource.crt_uid
     *
     * @mbggenerated
     */
    public void setCrtUid(Integer crtUid) {
        this.crtUid = crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.crt_host
     *
     * @return the value of base_group_resource.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.crt_host
     *
     * @param crtHost the value for base_group_resource.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.attr1
     *
     * @return the value of base_group_resource.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.attr1
     *
     * @param attr1 the value for base_group_resource.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.attr2
     *
     * @return the value of base_group_resource.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.attr2
     *
     * @param attr2 the value for base_group_resource.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_resource.attr3
     *
     * @return the value of base_group_resource.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_resource.attr3
     *
     * @param attr3 the value for base_group_resource.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }
}