package com.youmel.auth.pojo;

import java.util.Date;

public class BaseResourceAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.authority_id
     *
     * @mbggenerated
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.authority_type
     *
     * @mbggenerated
     */
    private String authorityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.resource_id
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.resource_type
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.crt_name
     *
     * @mbggenerated
     */
    private String crtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr6
     *
     * @mbggenerated
     */
    private String attr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr7
     *
     * @mbggenerated
     */
    private String attr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_resource_authority.attr8
     *
     * @mbggenerated
     */
    private String attr8;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    public BaseResourceAuthority(Integer id, String authorityId, String authorityType, String resourceId, String resourceType, String parentId, String path, String description, Date crtTime, String crtUser, String crtName, String crtHost, String attr1, String attr2, String attr3, String attr4, String attr5, String attr6, String attr7, String attr8) {
        this.id = id;
        this.authorityId = authorityId;
        this.authorityType = authorityType;
        this.resourceId = resourceId;
        this.resourceType = resourceType;
        this.parentId = parentId;
        this.path = path;
        this.description = description;
        this.crtTime = crtTime;
        this.crtUser = crtUser;
        this.crtName = crtName;
        this.crtHost = crtHost;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
        this.attr4 = attr4;
        this.attr5 = attr5;
        this.attr6 = attr6;
        this.attr7 = attr7;
        this.attr8 = attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource_authority
     *
     * @mbggenerated
     */
    public BaseResourceAuthority() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.id
     *
     * @return the value of base_resource_authority.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.id
     *
     * @param id the value for base_resource_authority.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.authority_id
     *
     * @return the value of base_resource_authority.authority_id
     *
     * @mbggenerated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.authority_id
     *
     * @param authorityId the value for base_resource_authority.authority_id
     *
     * @mbggenerated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.authority_type
     *
     * @return the value of base_resource_authority.authority_type
     *
     * @mbggenerated
     */
    public String getAuthorityType() {
        return authorityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.authority_type
     *
     * @param authorityType the value for base_resource_authority.authority_type
     *
     * @mbggenerated
     */
    public void setAuthorityType(String authorityType) {
        this.authorityType = authorityType == null ? null : authorityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.resource_id
     *
     * @return the value of base_resource_authority.resource_id
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.resource_id
     *
     * @param resourceId the value for base_resource_authority.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.resource_type
     *
     * @return the value of base_resource_authority.resource_type
     *
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.resource_type
     *
     * @param resourceType the value for base_resource_authority.resource_type
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.parent_id
     *
     * @return the value of base_resource_authority.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.parent_id
     *
     * @param parentId the value for base_resource_authority.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.path
     *
     * @return the value of base_resource_authority.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.path
     *
     * @param path the value for base_resource_authority.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.description
     *
     * @return the value of base_resource_authority.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.description
     *
     * @param description the value for base_resource_authority.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.crt_time
     *
     * @return the value of base_resource_authority.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.crt_time
     *
     * @param crtTime the value for base_resource_authority.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.crt_user
     *
     * @return the value of base_resource_authority.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.crt_user
     *
     * @param crtUser the value for base_resource_authority.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.crt_name
     *
     * @return the value of base_resource_authority.crt_name
     *
     * @mbggenerated
     */
    public String getCrtName() {
        return crtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.crt_name
     *
     * @param crtName the value for base_resource_authority.crt_name
     *
     * @mbggenerated
     */
    public void setCrtName(String crtName) {
        this.crtName = crtName == null ? null : crtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.crt_host
     *
     * @return the value of base_resource_authority.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.crt_host
     *
     * @param crtHost the value for base_resource_authority.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr1
     *
     * @return the value of base_resource_authority.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr1
     *
     * @param attr1 the value for base_resource_authority.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr2
     *
     * @return the value of base_resource_authority.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr2
     *
     * @param attr2 the value for base_resource_authority.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr3
     *
     * @return the value of base_resource_authority.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr3
     *
     * @param attr3 the value for base_resource_authority.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr4
     *
     * @return the value of base_resource_authority.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr4
     *
     * @param attr4 the value for base_resource_authority.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr5
     *
     * @return the value of base_resource_authority.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr5
     *
     * @param attr5 the value for base_resource_authority.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr6
     *
     * @return the value of base_resource_authority.attr6
     *
     * @mbggenerated
     */
    public String getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr6
     *
     * @param attr6 the value for base_resource_authority.attr6
     *
     * @mbggenerated
     */
    public void setAttr6(String attr6) {
        this.attr6 = attr6 == null ? null : attr6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr7
     *
     * @return the value of base_resource_authority.attr7
     *
     * @mbggenerated
     */
    public String getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr7
     *
     * @param attr7 the value for base_resource_authority.attr7
     *
     * @mbggenerated
     */
    public void setAttr7(String attr7) {
        this.attr7 = attr7 == null ? null : attr7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_resource_authority.attr8
     *
     * @return the value of base_resource_authority.attr8
     *
     * @mbggenerated
     */
    public String getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_resource_authority.attr8
     *
     * @param attr8 the value for base_resource_authority.attr8
     *
     * @mbggenerated
     */
    public void setAttr8(String attr8) {
        this.attr8 = attr8 == null ? null : attr8.trim();
    }
}