package com.youmel.auth.pojo;

public class BaseGroupMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.m_description
     *
     * @mbggenerated
     */
    private String mDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.m_type
     *
     * @mbggenerated
     */
    private Integer mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.crt_time
     *
     * @mbggenerated
     */
    private Integer crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.crt_uid
     *
     * @mbggenerated
     */
    private Integer crtUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.upd_time
     *
     * @mbggenerated
     */
    private Integer updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.upd_uid
     *
     * @mbggenerated
     */
    private Integer updUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_group_member.upd_host
     *
     * @mbggenerated
     */
    private String updHost;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    public BaseGroupMember(Integer id, Integer groupId, Integer userId, String mDescription, Integer mType, Integer crtTime, Integer crtUid, String crtHost, Integer updTime, Integer updUid, String updHost) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.mDescription = mDescription;
        this.mType = mType;
        this.crtTime = crtTime;
        this.crtUid = crtUid;
        this.crtHost = crtHost;
        this.updTime = updTime;
        this.updUid = updUid;
        this.updHost = updHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_group_member
     *
     * @mbggenerated
     */
    public BaseGroupMember() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.id
     *
     * @return the value of base_group_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.id
     *
     * @param id the value for base_group_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.group_id
     *
     * @return the value of base_group_member.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.group_id
     *
     * @param groupId the value for base_group_member.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.user_id
     *
     * @return the value of base_group_member.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.user_id
     *
     * @param userId the value for base_group_member.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.m_description
     *
     * @return the value of base_group_member.m_description
     *
     * @mbggenerated
     */
    public String getmDescription() {
        return mDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.m_description
     *
     * @param mDescription the value for base_group_member.m_description
     *
     * @mbggenerated
     */
    public void setmDescription(String mDescription) {
        this.mDescription = mDescription == null ? null : mDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.m_type
     *
     * @return the value of base_group_member.m_type
     *
     * @mbggenerated
     */
    public Integer getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.m_type
     *
     * @param mType the value for base_group_member.m_type
     *
     * @mbggenerated
     */
    public void setmType(Integer mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.crt_time
     *
     * @return the value of base_group_member.crt_time
     *
     * @mbggenerated
     */
    public Integer getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.crt_time
     *
     * @param crtTime the value for base_group_member.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Integer crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.crt_uid
     *
     * @return the value of base_group_member.crt_uid
     *
     * @mbggenerated
     */
    public Integer getCrtUid() {
        return crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.crt_uid
     *
     * @param crtUid the value for base_group_member.crt_uid
     *
     * @mbggenerated
     */
    public void setCrtUid(Integer crtUid) {
        this.crtUid = crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.crt_host
     *
     * @return the value of base_group_member.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.crt_host
     *
     * @param crtHost the value for base_group_member.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.upd_time
     *
     * @return the value of base_group_member.upd_time
     *
     * @mbggenerated
     */
    public Integer getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.upd_time
     *
     * @param updTime the value for base_group_member.upd_time
     *
     * @mbggenerated
     */
    public void setUpdTime(Integer updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.upd_uid
     *
     * @return the value of base_group_member.upd_uid
     *
     * @mbggenerated
     */
    public Integer getUpdUid() {
        return updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.upd_uid
     *
     * @param updUid the value for base_group_member.upd_uid
     *
     * @mbggenerated
     */
    public void setUpdUid(Integer updUid) {
        this.updUid = updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_group_member.upd_host
     *
     * @return the value of base_group_member.upd_host
     *
     * @mbggenerated
     */
    public String getUpdHost() {
        return updHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_group_member.upd_host
     *
     * @param updHost the value for base_group_member.upd_host
     *
     * @mbggenerated
     */
    public void setUpdHost(String updHost) {
        this.updHost = updHost == null ? null : updHost.trim();
    }
}