package com.youmel.auth.pojo;

public class BaseMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.href
     *
     * @mbggenerated
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_time
     *
     * @mbggenerated
     */
    private Integer crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_uid
     *
     * @mbggenerated
     */
    private Integer crtUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_time
     *
     * @mbggenerated
     */
    private Integer updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_uid
     *
     * @mbggenerated
     */
    private Integer updUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.upd_host
     *
     * @mbggenerated
     */
    private String updHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    public BaseMenu(Integer id, String title, Integer parentId, String href, String icon, Integer crtTime, Integer crtUid, String crtHost, Integer updTime, Integer updUid, String updHost, String attr1, String attr2, String attr3) {
        this.id = id;
        this.title = title;
        this.parentId = parentId;
        this.href = href;
        this.icon = icon;
        this.crtTime = crtTime;
        this.crtUid = crtUid;
        this.crtHost = crtHost;
        this.updTime = updTime;
        this.updUid = updUid;
        this.updHost = updHost;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    public BaseMenu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.id
     *
     * @return the value of base_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.id
     *
     * @param id the value for base_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.title
     *
     * @return the value of base_menu.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.title
     *
     * @param title the value for base_menu.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.parent_id
     *
     * @return the value of base_menu.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.parent_id
     *
     * @param parentId the value for base_menu.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.href
     *
     * @return the value of base_menu.href
     *
     * @mbggenerated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.href
     *
     * @param href the value for base_menu.href
     *
     * @mbggenerated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.icon
     *
     * @return the value of base_menu.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.icon
     *
     * @param icon the value for base_menu.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_time
     *
     * @return the value of base_menu.crt_time
     *
     * @mbggenerated
     */
    public Integer getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_time
     *
     * @param crtTime the value for base_menu.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Integer crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_uid
     *
     * @return the value of base_menu.crt_uid
     *
     * @mbggenerated
     */
    public Integer getCrtUid() {
        return crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_uid
     *
     * @param crtUid the value for base_menu.crt_uid
     *
     * @mbggenerated
     */
    public void setCrtUid(Integer crtUid) {
        this.crtUid = crtUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.crt_host
     *
     * @return the value of base_menu.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.crt_host
     *
     * @param crtHost the value for base_menu.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_time
     *
     * @return the value of base_menu.upd_time
     *
     * @mbggenerated
     */
    public Integer getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_time
     *
     * @param updTime the value for base_menu.upd_time
     *
     * @mbggenerated
     */
    public void setUpdTime(Integer updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_uid
     *
     * @return the value of base_menu.upd_uid
     *
     * @mbggenerated
     */
    public Integer getUpdUid() {
        return updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_uid
     *
     * @param updUid the value for base_menu.upd_uid
     *
     * @mbggenerated
     */
    public void setUpdUid(Integer updUid) {
        this.updUid = updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.upd_host
     *
     * @return the value of base_menu.upd_host
     *
     * @mbggenerated
     */
    public String getUpdHost() {
        return updHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.upd_host
     *
     * @param updHost the value for base_menu.upd_host
     *
     * @mbggenerated
     */
    public void setUpdHost(String updHost) {
        this.updHost = updHost == null ? null : updHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr1
     *
     * @return the value of base_menu.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr1
     *
     * @param attr1 the value for base_menu.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr2
     *
     * @return the value of base_menu.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr2
     *
     * @param attr2 the value for base_menu.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.attr3
     *
     * @return the value of base_menu.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.attr3
     *
     * @param attr3 the value for base_menu.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }
}