package com.youmel.auth.pojo;

import java.util.Date;

public class GateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.menu
     *
     * @mbggenerated
     */
    private String menu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.opt
     *
     * @mbggenerated
     */
    private String opt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.uri
     *
     * @mbggenerated
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.crt_name
     *
     * @mbggenerated
     */
    private String crtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gate_log.crt_host
     *
     * @mbggenerated
     */
    private String crtHost;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    public GateLog(Integer id, String menu, String opt, String uri, Date crtTime, String crtUser, String crtName, String crtHost) {
        this.id = id;
        this.menu = menu;
        this.opt = opt;
        this.uri = uri;
        this.crtTime = crtTime;
        this.crtUser = crtUser;
        this.crtName = crtName;
        this.crtHost = crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gate_log
     *
     * @mbggenerated
     */
    public GateLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.id
     *
     * @return the value of gate_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.id
     *
     * @param id the value for gate_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.menu
     *
     * @return the value of gate_log.menu
     *
     * @mbggenerated
     */
    public String getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.menu
     *
     * @param menu the value for gate_log.menu
     *
     * @mbggenerated
     */
    public void setMenu(String menu) {
        this.menu = menu == null ? null : menu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.opt
     *
     * @return the value of gate_log.opt
     *
     * @mbggenerated
     */
    public String getOpt() {
        return opt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.opt
     *
     * @param opt the value for gate_log.opt
     *
     * @mbggenerated
     */
    public void setOpt(String opt) {
        this.opt = opt == null ? null : opt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.uri
     *
     * @return the value of gate_log.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.uri
     *
     * @param uri the value for gate_log.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.crt_time
     *
     * @return the value of gate_log.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.crt_time
     *
     * @param crtTime the value for gate_log.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.crt_user
     *
     * @return the value of gate_log.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.crt_user
     *
     * @param crtUser the value for gate_log.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.crt_name
     *
     * @return the value of gate_log.crt_name
     *
     * @mbggenerated
     */
    public String getCrtName() {
        return crtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.crt_name
     *
     * @param crtName the value for gate_log.crt_name
     *
     * @mbggenerated
     */
    public void setCrtName(String crtName) {
        this.crtName = crtName == null ? null : crtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gate_log.crt_host
     *
     * @return the value of gate_log.crt_host
     *
     * @mbggenerated
     */
    public String getCrtHost() {
        return crtHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gate_log.crt_host
     *
     * @param crtHost the value for gate_log.crt_host
     *
     * @mbggenerated
     */
    public void setCrtHost(String crtHost) {
        this.crtHost = crtHost == null ? null : crtHost.trim();
    }
}