package com.youmel.auth.pojo;

public class TOrganizationUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.upd_uid
     *
     * @mbggenerated
     */
    private Integer updUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.upd_time
     *
     * @mbggenerated
     */
    private Integer updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    public TOrganizationUser(Integer id, Integer userId, Integer orgId, Integer updUid, Integer updTime, String status) {
        this.id = id;
        this.userId = userId;
        this.orgId = orgId;
        this.updUid = updUid;
        this.updTime = updTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization_user
     *
     * @mbggenerated
     */
    public TOrganizationUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.id
     *
     * @return the value of t_organization_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.id
     *
     * @param id the value for t_organization_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.user_id
     *
     * @return the value of t_organization_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.user_id
     *
     * @param userId the value for t_organization_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.org_id
     *
     * @return the value of t_organization_user.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.org_id
     *
     * @param orgId the value for t_organization_user.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.upd_uid
     *
     * @return the value of t_organization_user.upd_uid
     *
     * @mbggenerated
     */
    public Integer getUpdUid() {
        return updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.upd_uid
     *
     * @param updUid the value for t_organization_user.upd_uid
     *
     * @mbggenerated
     */
    public void setUpdUid(Integer updUid) {
        this.updUid = updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.upd_time
     *
     * @return the value of t_organization_user.upd_time
     *
     * @mbggenerated
     */
    public Integer getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.upd_time
     *
     * @param updTime the value for t_organization_user.upd_time
     *
     * @mbggenerated
     */
    public void setUpdTime(Integer updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization_user.status
     *
     * @return the value of t_organization_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization_user.status
     *
     * @param status the value for t_organization_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}